### ISSUE TITLE
IPv6 addresses are highlighted as resolvError

### ISSUE THREAD

**Issue by jamessan** [rid9/vim-resolv#1]
Given `/etc/resolv.conf` with these contents:

```
nameserver 2001:4dd0:200:304:53:2::3
nameserver 2001:4dd0:200:304:53:2::5
```

the addresses are highlighted with the `resolvError` highlight group.

**Comment by jamessan** [comment]
It looks like this was recently fixed in Vim [directly](https://github.com/vim/vim/commit/bc93cebb692f47488d66f078d1728031e9be35e7#diff-a1c9d69b41f1e8ba1adabc4329d2f3e0) by @djlucas.

**Comment by rid9** [comment]
@jamessan, just added IPv6 support in the latest version of the syntax file.

Bram accepted the changes and will integrate them soon. In the mean time, you can use the resolv.vim file on master (version 1.4).
