### ISSUE TITLE
Highlighted options are out of date

### ISSUE THREAD

**Issue by jamessan** [rid9/vim-resolv#2]
Some of the options documented in [resolv.conf(5)](https://manpages.debian.org/resolv.conf), including `single-request`, aren't recognized and get highlighted by the `resolvError` highlight group.

**Comment by rid9** [comment]
@jamessan, options updated in the latest version of the syntax file.

Bram accepted the changes and will integrate them soon. In the mean time, you can use the resolv.vim file on master (version 1.4).
